Repository PsycheFoundation/psyche, pull requests merged in 2025-09, with the labels that each got.

#264 bug: don't use uvloop for c10d store
  Cargo.lock
  python/extension-impl/Cargo.toml
  python/extension-impl/src/extension.rs
  python/python/psyche/sidecar/__main__.py
  shared/modeling/src/python_distributed_causal_lm.rs
  shared/modeling/src/python_distributed_trainer.rs
Labels: bug

#215 Show prompt tasks in frontend
  .gitignore
  shared/client/src/state/evals.rs
  shared/client/src/state/prompt.rs
  shared/client/src/state/prompt_texts.rs
  shared/client/src/state/stats.rs
  shared/coordinator/src/coordinator.rs
  website/backend/src/chainLoop.ts
  website/backend/src/dataStores/flatFileCoordinator.ts
  website/backend/src/index.ts
  website/frontend/package.json
  website/frontend/public/prompts/index.json
  website/frontend/src/components/PromptResults.tsx
  website/frontend/src/fakeData.ts
  website/frontend/src/routes/runs/$run.$index.tsx
  website/frontend/src/utils/prompts.ts
  website/frontend/src/utils/tokenizer.ts
  website/shared/index.ts
Labels: contract change

#308 feat(docker): add env vars to client image needed for triton config
  nix/docker.nix
Labels: code cleanup
